name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install-Target-WASM
        run: rustup target add wasm32-unknown-unknown
      - name: Build
        run: cargo build --target=wasm32-unknown-unknown --release
      - name: Package
        run: |
          mkdir -p ./etc/envoy
          build_repo_name=`echo ${GITHUB_REPOSITORY##*/} | tr '-' '_'`
          cp ./target/wasm32-unknown-unknown/release/${build_repo_name}.wasm ./etc/envoy/${build_repo_name}.wasm
          cp example/*.yaml ./etc/envoy/
          tar -zcf ./${build_repo_name}-${GITHUB_REF##*/}-wasm.tar.gz ./etc/envoy
          sha256sum ./${build_repo_name}-${GITHUB_REF##*/}-wasm.tar.gz >> ./${build_repo_name}-${GITHUB_REF##*/}.sha256sum
          bash ./.github/workflows/upload_asset.sh ./${build_repo_name}-${GITHUB_REF##*/}-wasm.tar.gz $GITHUB_TOKEN
      - name: Upload checksum
        run: |
          build_repo_name=`echo ${GITHUB_REPOSITORY##*/} | tr '-' '_'`
          bash ./.github/workflows/upload_asset.sh ./${build_repo_name}-${GITHUB_REF##*/}.sha256sum $GITHUB_TOKEN
