name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install-Target-WASM
        run: rustup target add wasm32-unknown-unknown
      - name: Build
        run: cargo build --target=wasm32-unknown-unknown --release
      - name: Package
        run: |
          mkdir -p ./etc/envoy
          cp ./target/wasm32-unknown-unknown/release/${GITHUB_REPOSITORY##*/}.wasm ./etc/envoy/${GITHUB_REPOSITORY##*/}.wasm
          cp example/*.yaml ./etc/envoy/
          tar -zcf ./${GITHUB_REPOSITORY##*/}-${GITHUB_REF##*/}-wasm.tar.gz ./etc/envoy
          sha256sum ./${GITHUB_REPOSITORY##*/}-${GITHUB_REF##*/}-wasm.tar.gz >> ./${GITHUB_REPOSITORY##*/}-${GITHUB_REF##*/}.sha256sum
          bash ./.github/workflows/upload_asset.sh ./${GITHUB_REPOSITORY##*/}-${GITHUB_REF##*/}-wasm.tar.gz $GITHUB_TOKEN
      - name: Upload checksum
        run: |
          bash ./.github/workflows/upload_asset.sh ./${GITHUB_REPOSITORY##*/}-${GITHUB_REF##*/}.sha256sum $GITHUB_TOKEN
