name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install-Target-WASM
        run: rustup target add wasm32-unknown-unknown
      - name: Build
        run: cargo build --target=wasm32-unknown-unknown --release
      - name: Package
        run: |
          cp ./target/wasm32-unknown-unknown/release/http_doh_auth_rs.wasm ./http_doh_auth_rs-${GITHUB_REF##*/}
          tar -zcf ./http_doh_auth_rs-${GITHUB_REF##*/}-linux.tar.gz ./http_doh_auth_rs-${GITHUB_REF##*/}
      - name: Upload executable
        run: |
          bash ./.github/workflows/upload_asset.sh \
            ./http_doh_auth_rs-${GITHUB_REF##*/}-linux.tar.gz $GITHUB_TOKEN
